include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - always_specify_types
    - sort_child_properties_last
    - avoid_print
    - prefer_final_locals
    - prefer_final_fields
    - avoid_unnecessary_containers
